upstream open_lms_upstream {
    server web:8000;
}

server {
    listen 80;
    server_name localhost; # Здесь можно указать IP сервера или домен

    # Максимальный размер загружаемых файлов (для медиа)
    client_max_body_size 20M;

    # Раздача статики
    location /static/ {
        alias /app/static/;
    }

    # Раздача медиафайлов
    location /media/ {
        alias /app/media/;
    }

    # Проксирование запросов на Gunicorn
    location / {
        proxy_pass http://open_lms_upstream;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded-for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }
}
