name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main", "master", "hw-nginx" ]
  pull_request:
    branches: [ "main", "master", "hw-nginx" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    # Кеширование зависимостей Poetry для ускорения пайплайна
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    # Этап Линтеры. Проверка качества кода
    - name: Lint with flake8
      run: |
        poetry run pip install flake8
        # Добавляем --exclude, чтобы исключить сторонние папки и автомиграции
        # poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,venv,env,migrations
        
        #  Выводим отчет об ошибках, но благодаря --exit-zero не останавливаем пайплайн
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv,venv,env,migrations

    # Этап Тестирования
    - name: Run tests
      env:
        SECRET_KEY: 'ci-test-secret-key'
        DEBUG: 'True'
        DB_ENGINE: 'django.db.backends.sqlite3' # Для тестов в CI используем легкую sqlite
      run: |
        poetry run python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push' # Деплоим только при коммите (в PR только тестируем)

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # Деплой на удаленный сервер через SSH-команды
    - name: Deploy to Remote Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          # Переходим в папку проекта (или создаем её)
          mkdir -p /home/${{ secrets.SSH_USER }}/open_lms
          cd /home/${{ secrets.SSH_USER }}/open_lms
          
          # Если репозиторий еще не клонирован на сервере, клонируем его, иначе обновляем
          if [ ! -d ".git" ]; then
            git clone https://github.com{{ github.repository }}.git .
          else
            git pull origin ${{ github.ref_name }}
          fi
          
          # Записываем секретные переменные из GitHub Secrets в файл .env на сервере
          echo "${{ secrets.ENV_FILE }}" > .env
          
          # Пересобираем и запускаем контейнеры в фоне (авто-перезапуск обеспечивается restart: always)
          docker-compose down
          docker-compose up --build -d
          
          # Очищаем неиспользуемые старые образы Docker для экономии места
          docker image prune -f
